# Generated by Django 2.0 on 2019-03-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0004_auto_20190320_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='last_name',
        ),
    ]
