# Generated by Django 2.0 on 2019-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0006_auto_20190321_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutriscore',
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_grade',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
