# Generated by Django 2.0 on 2019-03-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0009_auto_20190321_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsubstitute',
            name='product',
        ),
    ]
