# Generated by Django 2.0 on 2019-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0010_remove_savedsubstitute_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsubstitute',
            name='user',
            field=models.IntegerField(),
        ),
    ]
